---
# Homebrew role - Default variables

homebrew_installer_url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
homebrew_installer_path: "/tmp/homebrew-installer.sh"
homebrew_prefix: "/home/linuxbrew/.linuxbrew"
